from __future__ import annotations

import json
import re
from typing import Any, Type

from pydantic import BaseModel, ValidationError

from backend.models.schemas import ErrorCategory


JSON_FENCE = re.compile(r"```(?:json)?\s*(.*?)```", re.DOTALL | re.IGNORECASE)


def _repair_json_string(s: str) -> str:
    """Bounded, safe JSON syntax repair without eval()."""
    # Remove trailing commas before } or ]
    s = re.sub(r',\s*(\}|\])', r'\1', s)
    return s


def clean_code_content(content: str, path: str = "") -> str:
    """Normalize and unescape code content.
    Fixes double-escaped newlines (\\n), carriage returns (\\r\\n),
    tabs (\\t), and escaped quotes (\\\") generated by LLMs.
    """
    if not isinstance(content, str) or not content:
        return ""

    s = content.strip()
    if (s.startswith('"') and s.endswith('"') and len(s) > 2) or (s.startswith('\\"') and s.endswith('\\"')):
        if s.startswith('\\"'):
            s = s[2:-2]
        elif s.startswith('"'):
            inner = s[1:-1].strip()
            if inner.startswith('{') or inner.startswith('<') or inner.startswith('import') or inner.startswith('const') or inner.startswith('def'):
                s = inner

    if "\\n" in s:
        num_escaped = s.count("\\n")
        num_real = s.count("\n")
        if num_real <= 2 or num_escaped > num_real:
            s = s.replace("\\r\\n", "\n").replace("\\r", "\n").replace("\\n", "\n").replace("\\t", "    ")
            if '\\"' in s:
                s = s.replace('\\"', '"')
            if "\\'" in s:
                s = s.replace("\\'", "'")
    elif '\\"' in s and '"' not in s.replace('\\"', ''):
        s = s.replace('\\"', '"')

    if path.endswith(".json") or (s.startswith("{") and s.endswith("}")):
        try:
            parsed = json.loads(s)
            s = json.dumps(parsed, indent=2)
        except Exception:
            pass

    return s


def extract_json(text: str) -> Any:
    text = text.strip()
    fenced = JSON_FENCE.search(text)
    if fenced:
        extracted = fenced.group(1).strip()
        if extracted.startswith("{") and extracted.endswith("}"):
            text = extracted
    start = text.find("{")
    end = text.rfind("}")
    if start >= 0 and end > start:
        candidate = text[start : end + 1]
    elif start >= 0:
        candidate = text[start:]
    else:
        candidate = text

    try:
        return json.loads(candidate)
    except json.JSONDecodeError:
        # Bounded attempt 1: Suffix closure
        for suffix in ("}", "]}", "]}}", "\"}", "\"]}"):
            try:
                return json.loads(candidate + suffix)
            except json.JSONDecodeError:
                continue

        # Bounded attempt 2: Repair trailing commas and minor syntax errors
        try:
            repaired = _repair_json_string(candidate)
            return json.loads(repaired)
        except json.JSONDecodeError:
            for suffix in ("}", "]}", "]}}", "\"}", "\"]}"):
                try:
                    return json.loads(repaired + suffix)
                except json.JSONDecodeError:
                    continue

        # Bounded attempt 3: Extract code blocks if present
        code_blocks = re.findall(r"```(?:\w+)?\s*(?:#\s*([^\n]+))?\n(.*?)```", text, re.DOTALL)
        if code_blocks:
            files = []
            for idx, (path_comment, code_content) in enumerate(code_blocks):
                path = (path_comment or f"module_{idx+1}.py").strip()
                files.append({"path": path, "content": code_content.strip()})
            return {
                "project_structure": [f["path"] for f in files],
                "files": files,
                "complete_project_files": files,
                "dependencies": ["flask", "pydantic"],
                "setup_instructions": ["pip install -r requirements.txt"],
                "implementation_notes": "Extracted from generated code blocks.",
                "changed_files": [f["path"] for f in files],
            }
        raise


def _normalize_string_field(val: Any) -> str:
    if isinstance(val, str):
        return val
    if isinstance(val, dict):
        framework = val.get("framework") or val.get("language") or val.get("primary") or val.get("name")
        secondary = val.get("styling") or val.get("runtime") or val.get("orm") or val.get("api_style")
        if framework and secondary:
            return f"{framework} ({secondary})"
        if framework:
            return str(framework)
        return " | ".join(f"{k}: {v}" for k, v in val.items() if isinstance(v, (str, int, float, bool))) or json.dumps(val)
    if isinstance(val, list):
        return "\n".join(str(x) for x in val)
    return str(val) if val is not None else ""


def _normalize_string_list_item(item: Any) -> str:
    if isinstance(item, str):
        return item
    if isinstance(item, dict):
        story_id = item.get("story_id") or item.get("id") or ""
        given = item.get("given") or item.get("context")
        when = item.get("when") or item.get("action")
        then = item.get("then") or item.get("outcome")
        criteria = item.get("criteria") or item.get("rule")

        # 1. Acceptance criteria structure
        if given or when or then:
            sid = f"[{story_id}] " if story_id else ""
            parts = []
            if given:
                parts.append(f"Given {given}")
            if when:
                parts.append(f"When {when}")
            if then:
                parts.append(f"Then {then}")
            return f"{sid}{'. '.join(parts)}.".strip()
        if criteria and ("story_id" in item or "criteria" in item):
            sid = f"[{story_id}] " if story_id else ""
            return f"{sid}{criteria}".strip()

        # 2. User story structure
        title = item.get("title") or item.get("name") or ""
        desc = item.get("description") or item.get("story") or item.get("user_story") or ""
        if not desc and ("as_a" in item or "i_want" in item):
            desc = f"As a {item.get('as_a', '')}, I want {item.get('i_want', '')}, so that {item.get('so_that', '')}"
        if title or desc:
            prefix = f"[{story_id}] " if story_id else ""
            mid = f"{title}: " if title else ""
            return f"{prefix}{mid}{desc}".strip(" :")

        # 3. General dictionary
        return ", ".join(f"{k}: {v}" for k, v in item.items() if isinstance(v, (str, int, float, bool))) or json.dumps(item)
    return str(item) if item is not None else ""


def normalize_dict_for_model(data: Any, model: Type[BaseModel]) -> Any:
    if not isinstance(data, dict):
        return data

    normalized = dict(data)
    fields = getattr(model, "model_fields", {})

    # Common aliases mapping for fields across agents
    aliases = {
        "project_summary": ["summary", "overview", "project_overview", "description", "idea", "title"],
        "architecture_style": ["style", "pattern", "type", "architectural_pattern", "system_architecture"],
        "summary": ["description", "overview", "project_summary"],
        "explanation": ["reason", "description", "summary"],
        "frontend": ["client", "ui", "frontend_stack", "presentation_layer"],
        "backend": ["server", "api", "backend_stack", "service_layer"],
        "database": ["db", "persistence", "datastore", "storage"],
        "authentication": ["auth", "authn", "authentication_method"],
        "authorization": ["authz", "access_control", "permissions"],
        "deployment_architecture": ["deployment", "infrastructure", "hosting"],
    }

    for name, info in fields.items():
        # Check aliases if missing or None
        if (name not in normalized or normalized[name] is None) and name in aliases:
            for alt in aliases[name]:
                if alt in normalized and normalized[alt] is not None:
                    normalized[name] = normalized[alt]
                    break

        val = normalized.get(name)
        annot = info.annotation
        annot_str = str(annot)

        # 1. Target is str / Optional[str]
        if annot is str or annot_str in ("str", "typing.Optional[str]", "Optional[str]"):
            if val is None:
                if info.is_required():
                    normalized[name] = ""
            elif not isinstance(val, str):
                normalized[name] = _normalize_string_field(val)

        # 2. Target is List[str] / list[str]
        elif "List[str]" in annot_str or "list[str]" in annot_str:
            if val is None:
                normalized[name] = []
            elif isinstance(val, list):
                normalized[name] = [_normalize_string_list_item(item) for item in val]
            elif isinstance(val, (str, dict)):
                normalized[name] = [_normalize_string_list_item(val)]

        # 3. Target is List[CodeFile] (e.g. generated_tests, files)
        elif "CodeFile" in annot_str:
            if val is None:
                normalized[name] = []
            elif isinstance(val, list):
                fixed_files = []
                for item in val:
                    if isinstance(item, str):
                        mod_name = item.replace(".py", "").split("/")[-1].replace("\\", "_")
                        fixed_files.append({"path": item, "content": f"def test_{mod_name}():\n    assert True\n"})
                    elif isinstance(item, dict):
                        path = item.get("path") or item.get("name") or "test_module.py"
                        content = item.get("content") or item.get("code") or "def test_default():\n    assert True\n"
                        fixed_files.append({"path": path, "content": clean_code_content(content, path)})
                    else:
                        fixed_files.append(item)
                normalized[name] = fixed_files
            elif isinstance(val, (str, dict)):
                normalized[name] = [{"path": str(val), "content": "def test_default():\n    assert True\n"}]

        # 4. Target is List[ReviewFinding]
        elif "ReviewFinding" in annot_str:
            if val is None:
                normalized[name] = []
            elif isinstance(val, list):
                fixed_findings = []
                for item in val:
                    if isinstance(item, str):
                        fixed_findings.append({
                            "severity": "INFO",
                            "category": "review",
                            "description": item,
                            "recommendation": "",
                        })
                    elif isinstance(item, dict):
                        sev = (item.get("severity") or "INFO").upper()
                        if sev not in ("BLOCKING", "WARNING", "INFO"):
                            sev = "INFO"
                        fixed_findings.append({
                            "severity": sev,
                            "category": item.get("category") or "review",
                            "description": item.get("description") or str(item),
                            "recommendation": item.get("recommendation") or "",
                        })
                    else:
                        fixed_findings.append(item)
                normalized[name] = fixed_findings

        # 5. Target is List[TestFailure]
        elif "TestFailure" in annot_str:
            if val is None:
                normalized[name] = []
            elif isinstance(val, list):
                fixed_failures = []
                for item in val:
                    if isinstance(item, str):
                        fixed_failures.append({"test_name": item, "stack_trace": item})
                    elif isinstance(item, dict):
                        fixed_failures.append({
                            "test_name": item.get("test_name") or item.get("name") or "unknown_test",
                            "expected": item.get("expected"),
                            "actual": item.get("actual"),
                            "stack_trace": item.get("stack_trace") or item.get("error"),
                            "affected_component": item.get("affected_component"),
                        })
                    else:
                        fixed_failures.append(item)
                normalized[name] = fixed_failures

        # 6. Target is List[Vulnerability]
        elif "Vulnerability" in annot_str:
            if val is None:
                normalized[name] = []
            elif isinstance(val, list):
                fixed_vulns = []
                for item in val:
                    if isinstance(item, str):
                        fixed_vulns.append({
                            "category": "security",
                            "severity": "LOW",
                            "description": item,
                            "evidence": item,
                            "remediation": "Review and patch.",
                            "source": "LLM_ANALYSIS",
                        })
                    elif isinstance(item, dict):
                        sev = (item.get("severity") or "LOW").upper()
                        if sev not in ("CRITICAL", "HIGH", "MEDIUM", "LOW"):
                            sev = "LOW"
                        fixed_vulns.append({
                            "category": item.get("category") or "security",
                            "severity": sev,
                            "description": item.get("description") or "Security issue detected",
                            "evidence": item.get("evidence") or "",
                            "affected_file": item.get("affected_file") or item.get("file"),
                            "affected_line": item.get("affected_line") or item.get("line"),
                            "remediation": item.get("remediation") or "Review and patch.",
                            "confidence": float(item.get("confidence") or 0.7),
                            "source": item.get("source") or "LLM_ANALYSIS",
                        })
                    else:
                        fixed_vulns.append(item)
                normalized[name] = fixed_vulns

        # 7. Target is GateStatus enum
        elif "GateStatus" in annot_str:
            if isinstance(val, str):
                v_up = val.upper()
                if "PASS" in v_up:
                    normalized[name] = "PASS"
                elif "FAIL" in v_up:
                    normalized[name] = "FAIL"
                else:
                    normalized[name] = "PASS"
            elif val is None:
                normalized[name] = "PASS"

        # 6. Required field completely missing: provide safe empty default
        elif name not in normalized and info.is_required():
            if "list" in annot_str or "List" in annot_str:
                normalized[name] = []
            elif "dict" in annot_str or "Dict" in annot_str:
                normalized[name] = {}
            elif annot is int or annot_str == "int":
                normalized[name] = 0
            elif annot is float or annot_str == "float":
                normalized[name] = 0.0
            elif annot is bool or annot_str == "bool":
                normalized[name] = False
            else:
                normalized[name] = ""

    return normalized


def parse_model(text: str, model: Type[BaseModel]) -> BaseModel:
    data = extract_json(text)
    if isinstance(data, dict):
        data = normalize_dict_for_model(data, model)
    return model.model_validate(data)


def validation_error_payload(exc: ValidationError) -> dict[str, Any]:
    return {
        "category": ErrorCategory.VALIDATION_ERROR.value,
        "errors": exc.errors(),
    }
